## Laboratorium 2
### Łukasz Łuczyński


N = 9

Dataset: earthquake_data.csv

In [3]:
import pandas as pd
import csv

In [43]:
# Zczytywanie i uporządkowywanie danych
data = []
n = 1
with open('earthquake_data.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    for row in csv_reader:
        data.append(row)
data_dict = {}
for i in range(len(data[0])):
    data_dict[data[0][i]] = [row[i] for row in data[1:]]

In [49]:
# Stworzenie DataFrame'u
df = pd.DataFrame(data_dict)
df

,"In general, how worried are you about earthquakes?","How worried are you about the Big One, a massive, catastrophic earthquake?","Do you think the ""Big One"" will occur in your lifetime?",Have you ever experienced an earthquake?,"Have you or anyone in your household taken any precautions for an earthquake (packed an earthquake survival kit, prepared an evacuation plan, etc.)?",How familiar are you with the San Andreas Fault line?,How familiar are you with the Yellowstone Supervolcano?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
0,Not at all worried,Not so worried,No,"Yes, one or more minor ones",No,Somewhat familiar,Not so familiar,18 - 29,Male,Prefer not to answer,New England
1,Somewhat worried,Very worried,No,"Yes, one or more minor ones",No,Not at all familiar,Not at all familiar,18 - 29,Male,"$75,000 to $99,999",East North Central
2,Not so worried,Somewhat worried,No,"Yes, one or more minor ones",No,Very familiar,Somewhat familiar,18 - 29,Male,"$10,000 to $24,999",Pacific
3,Not so worried,Not so worried,No,"Yes, one or more minor ones",No,Very familiar,Not so familiar,18 - 29,Male,"$25,000 to $49,999",West South Central
4,Not so worried,Not so worried,Yes,"Yes, one or more minor ones",No,Somewhat familiar,Extremely familiar,18 - 29,Male,"$200,000 and up",Middle Atlantic
...,...,...,...,...,...,...,...,...,...,...,...
1008,Not at all worried,Not at all worried,No,"Yes, one or more minor ones",No,Very familiar,Not so familiar,60,Male,Prefer not to answer,Pacific
1009,Not so worried,Somewhat worried,No,"Yes, one or more major ones",Yes,Extremely familiar,Somewhat familiar,60,Female,"$50,000 to $74,999",Pacific
1010,Not so worried,Extremely worried,No,"Yes, one or more minor ones",No,Somewhat familiar,Somewhat familiar,30 - 44,Female,Prefer not to answer,Middle Atlantic
1011,Not at all worried,Not so worried,No,No,No,Somewhat familiar,Somewhat familiar,30 - 44,Female,"$50,000 to $74,999",East North Central
1012,Somewhat worried,Not so worried,No,"Yes, one or more minor ones",No,,,,,,

In [55]:
df.describe()

,"In general, how worried are you about earthquakes?","How worried are you about the Big One, a massive, catastrophic earthquake?","Do you think the ""Big One"" will occur in your lifetime?",Have you ever experienced an earthquake?,"Have you or anyone in your household taken any precautions for an earthquake (packed an earthquake survival kit, prepared an evacuation plan, etc.)?",How familiar are you with the San Andreas Fault line?,How familiar are you with the Yellowstone Supervolcano?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
count,1013,1013,1013,1013,1013,1013,1013,1013,1013,1013,1013
unique,5,5,2,4,3,6,6,5,3,12,10
top,Not at all worried,Not at all worried,No,"Yes, one or more minor ones",No,Somewhat familiar,Somewhat familiar,45 - 59,Female,"$50,000 to $74,999",Pacific
freq,356,334,577,483,788,397,280,275,521,175,206

In [64]:
df[data[0][0]].value_counts()

Not at all worried    356
Not so worried        327
Somewhat worried      223
Very worried           54
Extremely worried      53
Name: In general, how worried are you about earthquakes?, dtype: int64

In [72]:
df2 = df[['Age','What is your gender?','Do you think the "Big One" will occur in your lifetime?']]
df2

,Age,What is your gender?,"Do you think the ""Big One"" will occur in your lifetime?"
0,18 - 29,Male,No
1,18 - 29,Male,No
2,18 - 29,Male,No
3,18 - 29,Male,No
4,18 - 29,Male,Yes
...,...,...,...
1008,60,Male,No
1009,60,Female,No
1010,30 - 44,Female,No
1011,30 - 44,Female,No
1012,,,No